### ISSUE TITLE
koa-jwt with koa-router

### ISSUE THREAD

**Issue by graemefunk87** [stiang/koa-jwt#13]
I'm trying to implement this with koa-router and I can't seem to get it work, I'm somewhat new to koa so I'm sure I'm just misunderstanding something in the koa architecture, but is there a way to get these two modules to play nice?

**Comment by clthck** [comment]
I tested the following way with koa@1.x and it works.

```javascript
const koa = require('koa');
const jwt = require('koa-jwt');
const routers = {
  unauthenticated: new Router(),
  authenticated: new Router()
};

const app = koa();

app.use(routers.unauthenticated.routes());
app.use(routers.unauthenticated.allowedMethods());

routers.unauthenticated.use(jwt({ secret: process.env.JWT_SHARED_SECRET }));
app.use(routers.authenticated.routes());
app.use(routers.authenticated.allowedMethods());

app.listen(3000);
```

Not sure about whether it will work with koa@2
