### ISSUE TITLE
jsonwebtoken 5.0.0

### ISSUE THREAD

**Issue by vanthiyathevan** [stiang/koa-jwt#15]
Is this getting updated soon? getting npm deprecated warning 
```
npm WARN deprecated jsonwebtoken@4.2.2: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
```

**Comment by stiang** [comment]
Huh, I thought 4.2.2 fixed the vuln. Anyway, I just cut a new release (0.1.10) using 5.0.0. Thanks for the heads-up!
